package hitz.virtuozo.ui;

import hitz.virtuozo.ui.api.HasText;
import hitz.virtuozo.ui.api.Icon;
import hitz.virtuozo.ui.api.UIComponent;

import com.google.gwt.dom.client.SpanElement;

public enum FontAwesome implements Icon {
  EYEDROPPER( "fa-eyedropper"),
  FUTBOL_O( "fa-futbol-o"),
  NEWSPAPER_O( "fa-newspaper-o"),
  PAINT_BRUSH( "fa-paint-brush"),
  PLUG( "fa-plug"),
  SOCCER_BALL_O( "fa-soccer-ball-o"),
  TOGGLE_OFF( "fa-toggle-off"),
  TOGGLE_ON( "fa-toggle-on"),
  TRASH( "fa-trash"),
  TTY( "fa-tty"),
  WIFI( "fa-wifi"),
  ADJUST( "fa-adjust"),
  ANCHOR( "fa-anchor"),
  ARCHIVE( "fa-archive"),
  ASTERISK( "fa-asterisk"),
  AT( "fa-at"),
  AUTOMOBILE( "fa-automobile"),
  BAN( "fa-ban"),
  BANK( "fa-bank"),
  BARCODE( "fa-barcode"),
  BARS( "fa-bars"),
  BEER( "fa-beer"),
  BELL( "fa-bell"),
  BELL_O( "fa-bell-o"),
  BELL_SLASH( "fa-bell-slash"),
  BELL_SLASH_O( "fa-bell-slash-o"),
  BICYCLE( "fa-bicycle"),
  BINOCULARS( "fa-binoculars"),
  BIRTHDAY_CAKE( "fa-birthday-cake"),
  BOLT( "fa-bolt"),
  BOMB( "fa-bomb"),
  BOOK( "fa-book"),
  BOOKMARK( "fa-bookmark"),
  BOOKMARK_O( "fa-bookmark-o"),
  BRIEFCASE( "fa-briefcase"),
  BUG( "fa-bug"),
  BUILDING( "fa-building"),
  BUILDING_O( "fa-building-o"),
  BULLHORN( "fa-bullhorn"),
  BULLSEYE( "fa-bullseye"),
  BUS( "fa-bus"),
  CAB( "fa-cab"),
  CALCULATOR( "fa-calculator"),
  CALENDAR( "fa-calendar"),
  CALENDAR_O( "fa-calendar-o"),
  CAMERA( "fa-camera"),
  CAMERA_RETRO( "fa-camera-retro"),
  CAR( "fa-car"),
  CC( "fa-cc"),
  CERTIFICATE( "fa-certificate"),
  CHECK( "fa-check"),
  CHECK_CIRCLE( "fa-check-circle"),
  CHECK_CIRCLE_O( "fa-check-circle-o"),
  CHILD( "fa-child"),
  CIRCLE_THIN( "fa-circle-thin"),
  CLOCK_O( "fa-clock-o"),
  CLOSE( "fa-close"),
  CLOUD( "fa-cloud"),
  CLOUD_DOWNLOAD( "fa-cloud-download"),
  CLOUD_UPLOAD( "fa-cloud-upload"),
  CODE( "fa-code"),
  CODE_FORK( "fa-code-fork"),
  COFFEE( "fa-coffee"),
  COGS( "fa-cogs"),
  COMMENT( "fa-comment"),
  COMMENT_O( "fa-comment-o"),
  COMMENTS( "fa-comments"),
  COMMENTS_O( "fa-comments-o"),
  COMPASS( "fa-compass"),
  COPYRIGHT( "fa-copyright"),
  CROP( "fa-crop"),
  CROSSHAIRS( "fa-crosshairs"),
  CUBE( "fa-cube"),
  CUBES( "fa-cubes"),
  CUTLERY( "fa-cutlery"),
  DASHBOARD( "fa-dashboard"),
  DATABASE( "fa-database"),
  DESKTOP( "fa-desktop"),
  DOWNLOAD( "fa-download"),
  EDIT( "fa-edit"),
  ELLIPSIS_H( "fa-ellipsis-h"),
  ELLIPSIS_V( "fa-ellipsis-v"),
  ENVELOPE( "fa-envelope"),
  ENVELOPE_O( "fa-envelope-o"),
  ENVELOPE_SQUARE( "fa-envelope-square"),
  EXCHANGE( "fa-exchange"),
  EXCLAMATION( "fa-exclamation"),
  EXCLAMATION_CIRCLE( "fa-exclamation-circle"),
  EXCLAMATION_TRIANGLE( "fa-exclamation-triangle"),
  EXTERNAL_LINK( "fa-external-link"),
  EXTERNAL_LINK_SQUARE( "fa-external-link-square"),
  EYE( "fa-eye"),
  EYE_SLASH( "fa-eye-slash"),
  FAX( "fa-fax"),
  FEMALE( "fa-female"),
  FIGHTER_JET( "fa-fighter-jet"),
  FILM( "fa-film"),
  FILTER( "fa-filter"),
  FIRE( "fa-fire"),
  FIRE_EXTINGUISHER( "fa-fire-extinguisher"),
  FLAG( "fa-flag"),
  FLAG_CHECKERED( "fa-flag-checkered"),
  FLAG_O( "fa-flag-o"),
  FLASH( "fa-flash"),
  FLASK( "fa-flask"),
  FOLDER( "fa-folder"),
  FOLDER_O( "fa-folder-o"),
  FOLDER_OPEN( "fa-folder-open"),
  FOLDER_OPEN_O( "fa-folder-open-o"),
  FROWN_O( "fa-frown-o"),
  GAMEPAD( "fa-gamepad"),
  GAVEL( "fa-gavel"),
  GEARS( "fa-gears"),
  GIFT( "fa-gift"),
  GLASS( "fa-glass"),
  GLOBE( "fa-globe"),
  GRADUATION_CAP( "fa-graduation-cap"),
  GROUP( "fa-group"),
  HDD_O( "fa-hdd-o"),
  HEADPHONES( "fa-headphones"),
  HEART( "fa-heart"),
  HEART_O( "fa-heart-o"),
  HISTORY( "fa-history"),
  HOME( "fa-home"),
  IMAGE( "fa-image"),
  INBOX( "fa-inbox"),
  INFO( "fa-info"),
  INFO_CIRCLE( "fa-info-circle"),
  INSTITUTION( "fa-institution"),
  KEY( "fa-key"),
  KEYBOARD_O( "fa-keyboard-o"),
  LANGUAGE( "fa-language"),
  LAPTOP( "fa-laptop"),
  LEAF( "fa-leaf"),
  LEGAL( "fa-legal"),
  LEMON_O( "fa-lemon-o"),
  LEVEL_DOWN( "fa-level-down"),
  LEVEL_UP( "fa-level-up"),
  LIFE_BUOY( "fa-life-buoy"),
  LIFE_RING( "fa-life-ring"),
  LIFE_SAVER( "fa-life-saver"),
  LIGHTBULB_O( "fa-lightbulb-o"),
  LOCATION_ARROW( "fa-location-arrow"),
  LOCK( "fa-lock"),
  MAGIC( "fa-magic"),
  MAGNET( "fa-magnet"),
  MAIL_FORWARD( "fa-mail-forward"),
  MAIL_REPLY( "fa-mail-reply"),
  MAIL_REPLY_ALL( "fa-mail-reply-all"),
  MALE( "fa-male"),
  MAP_MARKER( "fa-map-marker"),
  MEH_O( "fa-meh-o"),
  MICROPHONE( "fa-microphone"),
  MICROPHONE_SLASH( "fa-microphone-slash"),
  MINUS( "fa-minus"),
  MINUS_CIRCLE( "fa-minus-circle"),
  MOBILE( "fa-mobile"),
  MOBILE_PHONE( "fa-mobile-phone"),
  MOON_O( "fa-moon-o"),
  MORTAR_BOARD( "fa-mortar-board"),
  MUSIC( "fa-music"),
  NAVICON( "fa-navicon"),
  PAPER_PLANE( "fa-paper-plane"),
  PAPER_PLANE_O( "fa-paper-plane-o"),
  PAW( "fa-paw"),
  PENCIL( "fa-pencil"),
  PENCIL_SQUARE( "fa-pencil-square"),
  PENCIL_SQUARE_O( "fa-pencil-square-o"),
  PHONE( "fa-phone"),
  PHONE_SQUARE( "fa-phone-square"),
  PHOTO( "fa-photo"),
  PICTURE_O( "fa-picture-o"),
  PLANE( "fa-plane"),
  PLUS( "fa-plus"),
  PLUS_CIRCLE( "fa-plus-circle"),
  POWER_OFF( "fa-power-off"),
  PRINT( "fa-print"),
  PUZZLE_PIECE( "fa-puzzle-piece"),
  QRCODE( "fa-qrcode"),
  QUESTION( "fa-question"),
  QUESTION_CIRCLE( "fa-question-circle"),
  QUOTE_LEFT( "fa-quote-left"),
  QUOTE_RIGHT( "fa-quote-right"),
  RANDOM( "fa-random"),
  RECYCLE( "fa-recycle"),
  REMOVE( "fa-remove"),
  REORDER( "fa-reorder"),
  REPLY( "fa-reply"),
  REPLY_ALL( "fa-reply-all"),
  RETWEET( "fa-retweet"),
  ROAD( "fa-road"),
  ROCKET( "fa-rocket"),
  RSS( "fa-rss"),
  RSS_SQUARE( "fa-rss-square"),
  SEARCH( "fa-search"),
  SEARCH_MINUS( "fa-search-minus"),
  SEARCH_PLUS( "fa-search-plus"),
  SEND( "fa-send"),
  SEND_O( "fa-send-o"),
  SHARE( "fa-share"),
  SHARE_SQUARE( "fa-share-square"),
  SHARE_SQUARE_O( "fa-share-square-o"),
  SHIELD( "fa-shield"),
  SHOPPING_CART( "fa-shopping-cart"),
  SIGN_IN( "fa-sign-in"),
  SIGN_OUT( "fa-sign-out"),
  SIGNAL( "fa-signal"),
  SITEMAP( "fa-sitemap"),
  SLIDERS( "fa-sliders"),
  SMILE_O( "fa-smile-o"),
  SORT( "fa-sort"),
  SORT_ALPHA_ASC( "fa-sort-alpha-asc"),
  SORT_ALPHA_DESC( "fa-sort-alpha-desc"),
  SORT_AMOUNT_ASC( "fa-sort-amount-asc"),
  SORT_AMOUNT_DESC( "fa-sort-amount-desc"),
  SORT_ASC( "fa-sort-asc"),
  SORT_DESC( "fa-sort-desc"),
  SORT_DOWN( "fa-sort-down"),
  SORT_NUMERIC_ASC( "fa-sort-numeric-asc"),
  SORT_NUMERIC_DESC( "fa-sort-numeric-desc"),
  SORT_UP( "fa-sort-up"),
  SPACE_SHUTTLE( "fa-space-shuttle"),
  SPOON( "fa-spoon"),
  STAR( "fa-star"),
  STAR_HALF( "fa-star-half"),
  STAR_HALF_EMPTY( "fa-star-half-empty"),
  STAR_HALF_FULL( "fa-star-half-full"),
  STAR_HALF_O( "fa-star-half-o"),
  STAR_O( "fa-star-o"),
  SUITCASE( "fa-suitcase"),
  SUN_O( "fa-sun-o"),
  SUPPORT( "fa-support"),
  TABLET( "fa-tablet"),
  TACHOMETER( "fa-tachometer"),
  TAG( "fa-tag"),
  TAGS( "fa-tags"),
  TASKS( "fa-tasks"),
  TAXI( "fa-taxi"),
  TERMINAL( "fa-terminal"),
  THUMB_TACK( "fa-thumb-tack"),
  THUMBS_DOWN( "fa-thumbs-down"),
  THUMBS_O_DOWN( "fa-thumbs-o-down"),
  THUMBS_O_UP( "fa-thumbs-o-up"),
  THUMBS_UP( "fa-thumbs-up"),
  TICKET( "fa-ticket"),
  TIMES( "fa-times"),
  TIMES_CIRCLE( "fa-times-circle"),
  TIMES_CIRCLE_O( "fa-times-circle-o"),
  TINT( "fa-tint"),
  TRASH_O( "fa-trash-o"),
  TREE( "fa-tree"),
  TROPHY( "fa-trophy"),
  TRUCK( "fa-truck"),
  UMBRELLA( "fa-umbrella"),
  UNIVERSITY( "fa-university"),
  UNLOCK( "fa-unlock"),
  UNLOCK_ALT( "fa-unlock-alt"),
  UNSORTED( "fa-unsorted"),
  UPLOAD( "fa-upload"),
  USER( "fa-user"),
  USERS( "fa-users"),
  VIDEO_CAMERA( "fa-video-camera"),
  VOLUME_DOWN( "fa-volume-down"),
  VOLUME_OFF( "fa-volume-off"),
  VOLUME_UP( "fa-volume-up"),
  WARNING( "fa-warning"),
  WRENCH( "fa-wrench"),
  FILE( "fa-file"),
  FILE_ARCHIVE_O( "fa-file-archive-o"),
  FILE_AUDIO_O( "fa-file-audio-o"),
  FILE_CODE_O( "fa-file-code-o"),
  FILE_EXCEL_O( "fa-file-excel-o"),
  FILE_IMAGE_O( "fa-file-image-o"),
  FILE_MOVIE_O( "fa-file-movie-o"),
  FILE_O( "fa-file-o"),
  FILE_PDF_O( "fa-file-pdf-o"),
  FILE_PHOTO_O( "fa-file-photo-o"),
  FILE_PICTURE_O( "fa-file-picture-o"),
  FILE_POWERPOINT_O( "fa-file-powerpoint-o"),
  FILE_SOUND_O( "fa-file-sound-o"),
  FILE_TEXT( "fa-file-text"),
  FILE_TEXT_O( "fa-file-text-o"),
  FILE_VIDEO_O( "fa-file-video-o"),
  FILE_WORD_O( "fa-file-word-o"),
  FILE_ZIP_O( "fa-file-zip-o"),
  CIRCLE_O_NOTCH( "fa-circle-o-notch fa-spin"),
  COG( "fa-cog fa-spin"),
  GEAR( "fa-gear"),
  REFRESH( "fa-refresh fa-spin"),
  SPINNER( "fa-spinner fa-spin"),
  CHECK_SQUARE( "fa-check-square"),
  CHECK_SQUARE_O( "fa-check-square-o"),
  CIRCLE( "fa-circle"),
  CIRCLE_O( "fa-circle-o"),
  DOT_CIRCLE_O( "fa-dot-circle-o"),
  MINUS_SQUARE( "fa-minus-square"),
  MINUS_SQUARE_O( "fa-minus-square-o"),
  PLUS_SQUARE_O( "fa-plus-square-o"),
  SQUARE( "fa-square"),
  SQUARE_O( "fa-square-o"),
  CREDIT_CARD( "fa-credit-card"),
  AREA_CHART( "fa-area-chart"),
  BAR_CHART( "fa-bar-chart"),
  BAR_CHART_O( "fa-bar-chart-o"),
  LINE_CHART( "fa-line-chart"),
  PIE_CHART( "fa-pie-chart"),
  CNY( "fa-cny"),
  DOLLAR( "fa-dollar"),
  EUR( "fa-eur"),
  EURO( "fa-euro"),
  GBP( "fa-gbp"),
  ILS( "fa-ils"),
  INR( "fa-inr"),
  JPY( "fa-jpy"),
  KRW( "fa-krw"),
  MONEY( "fa-money"),
  RMB( "fa-rmb"),
  ROUBLE( "fa-rouble"),
  RUB( "fa-rub"),
  RUBLE( "fa-ruble"),
  RUPEE( "fa-rupee"),
  SHEKEL( "fa-shekel"),
  SHEQEL( "fa-sheqel"),
  TRY( "fa-try"),
  TURKISH_LIRA( "fa-turkish-lira"),
  USD( "fa-usd"),
  WON( "fa-won"),
  YEN( "fa-yen"),
  ALIGN_CENTER( "fa-align-center"),
  ALIGN_JUSTIFY( "fa-align-justify"),
  ALIGN_LEFT( "fa-align-left"),
  ALIGN_RIGHT( "fa-align-right"),
  BOLD( "fa-bold"),
  CHAIN( "fa-chain"),
  CHAIN_BROKEN( "fa-chain-broken"),
  CLIPBOARD( "fa-clipboard"),
  COLUMNS( "fa-columns"),
  COPY( "fa-copy"),
  CUT( "fa-cut"),
  DEDENT( "fa-dedent"),
  ERASER( "fa-eraser"),
  FILES_O( "fa-files-o"),
  FLOPPY_O( "fa-floppy-o"),
  FONT( "fa-font"),
  HEADER( "fa-header"),
  INDENT( "fa-indent"),
  ITALIC( "fa-italic"),
  LINK( "fa-link"),
  LIST( "fa-list"),
  LIST_ALT( "fa-list-alt"),
  LIST_OL( "fa-list-ol"),
  LIST_UL( "fa-list-ul"),
  OUTDENT( "fa-outdent"),
  PAPERCLIP( "fa-paperclip"),
  PARAGRAPH( "fa-paragraph"),
  PASTE( "fa-paste"),
  REPEAT( "fa-repeat"),
  ROTATE_LEFT( "fa-rotate-left"),
  ROTATE_RIGHT( "fa-rotate-right"),
  SAVE( "fa-save"),
  SCISSORS( "fa-scissors"),
  STRIKETHROUGH( "fa-strikethrough"),
  SUBSCRIPT( "fa-subscript"),
  SUPERSCRIPT( "fa-superscript"),
  TABLE( "fa-table"),
  TEXT_HEIGHT( "fa-text-height"),
  TEXT_WIDTH( "fa-text-width"),
  TH( "fa-th"),
  TH_LARGE( "fa-th-large"),
  TH_LIST( "fa-th-list"),
  UNDERLINE( "fa-underline"),
  UNDO( "fa-undo"),
  UNLINK( "fa-unlink"),
  ANGLE_DOUBLE_DOWN( "fa-angle-double-down"),
  ANGLE_DOUBLE_LEFT( "fa-angle-double-left"),
  ANGLE_DOUBLE_RIGHT( "fa-angle-double-right"),
  ANGLE_DOUBLE_UP( "fa-angle-double-up"),
  ANGLE_DOWN( "fa-angle-down"),
  ANGLE_LEFT( "fa-angle-left"),
  ANGLE_RIGHT( "fa-angle-right"),
  ANGLE_UP( "fa-angle-up"),
  ARROW_CIRCLE_DOWN( "fa-arrow-circle-down"),
  ARROW_CIRCLE_LEFT( "fa-arrow-circle-left"),
  ARROW_CIRCLE_O_DOWN( "fa-arrow-circle-o-down"),
  ARROW_CIRCLE_O_LEFT( "fa-arrow-circle-o-left"),
  ARROW_CIRCLE_O_RIGHT( "fa-arrow-circle-o-right"),
  ARROW_CIRCLE_O_UP( "fa-arrow-circle-o-up"),
  ARROW_CIRCLE_RIGHT( "fa-arrow-circle-right"),
  ARROW_CIRCLE_UP( "fa-arrow-circle-up"),
  ARROW_DOWN( "fa-arrow-down"),
  ARROW_LEFT( "fa-arrow-left"),
  ARROW_RIGHT( "fa-arrow-right"),
  ARROW_UP( "fa-arrow-up"),
  ARROWS( "fa-arrows"),
  ARROWS_H( "fa-arrows-h"),
  ARROWS_V( "fa-arrows-v"),
  CARET_DOWN( "fa-caret-down"),
  CARET_LEFT( "fa-caret-left"),
  CARET_RIGHT( "fa-caret-right"),
  CARET_SQUARE_O_DOWN( "fa-caret-square-o-down"),
  CARET_SQUARE_O_LEFT( "fa-caret-square-o-left"),
  CARET_SQUARE_O_RIGHT( "fa-caret-square-o-right"),
  CARET_SQUARE_O_UP( "fa-caret-square-o-up"),
  CARET_UP( "fa-caret-up"),
  CHEVRON_CIRCLE_DOWN( "fa-chevron-circle-down"),
  CHEVRON_CIRCLE_LEFT( "fa-chevron-circle-left"),
  CHEVRON_CIRCLE_RIGHT( "fa-chevron-circle-right"),
  CHEVRON_CIRCLE_UP( "fa-chevron-circle-up"),
  CHEVRON_DOWN( "fa-chevron-down"),
  CHEVRON_LEFT( "fa-chevron-left"),
  CHEVRON_RIGHT( "fa-chevron-right"),
  CHEVRON_UP( "fa-chevron-up"),
  HAND_O_DOWN( "fa-hand-o-down"),
  HAND_O_LEFT( "fa-hand-o-left"),
  HAND_O_RIGHT( "fa-hand-o-right"),
  HAND_O_UP( "fa-hand-o-up"),
  LONG_ARROW_DOWN( "fa-long-arrow-down"),
  LONG_ARROW_LEFT( "fa-long-arrow-left"),
  LONG_ARROW_RIGHT( "fa-long-arrow-right"),
  LONG_ARROW_UP( "fa-long-arrow-up"),
  TOGGLE_DOWN( "fa-toggle-down"),
  TOGGLE_LEFT( "fa-toggle-left"),
  TOGGLE_RIGHT( "fa-toggle-right"),
  TOGGLE_UP( "fa-toggle-up"),
  ARROWS_ALT( "fa-arrows-alt"),
  BACKWARD( "fa-backward"),
  COMPRESS( "fa-compress"),
  EJECT( "fa-eject"),
  EXPAND( "fa-expand"),
  FAST_BACKWARD( "fa-fast-backward"),
  FAST_FORWARD( "fa-fast-forward"),
  FORWARD( "fa-forward"),
  PAUSE( "fa-pause"),
  PLAY( "fa-play"),
  PLAY_CIRCLE( "fa-play-circle"),
  PLAY_CIRCLE_O( "fa-play-circle-o"),
  STEP_BACKWARD( "fa-step-backward"),
  STEP_FORWARD( "fa-step-forward"),
  STOP( "fa-stop"),
  ADN( "fa-adn"),
  ANDROID( "fa-android"),
  ANGELLIST( "fa-angellist"),
  APPLE( "fa-apple"),
  BEHANCE( "fa-behance"),
  BEHANCE_SQUARE( "fa-behance-square"),
  BITBUCKET( "fa-bitbucket"),
  BITBUCKET_SQUARE( "fa-bitbucket-square"),
  BITCOIN( "fa-bitcoin"),
  BTC( "fa-btc"),
  CC_AMEX( "fa-cc-amex"),
  CC_DISCOVER( "fa-cc-discover"),
  CC_MASTERCARD( "fa-cc-mastercard"),
  CC_PAYPAL( "fa-cc-paypal"),
  CC_STRIPE( "fa-cc-stripe"),
  CC_VISA( "fa-cc-visa"),
  CODEPEN( "fa-codepen"),
  CSS3( "fa-css3"),
  DELICIOUS( "fa-delicious"),
  DEVIANTART( "fa-deviantart"),
  DIGG( "fa-digg"),
  DRIBBBLE( "fa-dribbble"),
  DROPBOX( "fa-dropbox"),
  DRUPAL( "fa-drupal"),
  EMPIRE( "fa-empire"),
  FACEBOOK( "fa-facebook"),
  FACEBOOK_SQUARE( "fa-facebook-square"),
  FLICKR( "fa-flickr"),
  FOURSQUARE( "fa-foursquare"),
  GE( "fa-ge"),
  GIT( "fa-git"),
  GIT_SQUARE( "fa-git-square"),
  GITHUB( "fa-github"),
  GITHUB_ALT( "fa-github-alt"),
  GITHUB_SQUARE( "fa-github-square"),
  GITTIP( "fa-gittip"),
  GOOGLE( "fa-google"),
  GOOGLE_PLUS( "fa-google-plus"),
  GOOGLE_PLUS_SQUARE( "fa-google-plus-square"),
  GOOGLE_WALLET( "fa-google-wallet"),
  HACKER_NEWS( "fa-hacker-news"),
  HTML5( "fa-html5"),
  INSTAGRAM( "fa-instagram"),
  IOXHOST( "fa-ioxhost"),
  JOOMLA( "fa-joomla"),
  JSFIDDLE( "fa-jsfiddle"),
  LASTFM( "fa-lastfm"),
  LASTFM_SQUARE( "fa-lastfm-square"),
  LINKEDIN( "fa-linkedin"),
  LINKEDIN_SQUARE( "fa-linkedin-square"),
  LINUX( "fa-linux"),
  MAXCDN( "fa-maxcdn"),
  MEANPATH( "fa-meanpath"),
  OPENID( "fa-openid"),
  PAGELINES( "fa-pagelines"),
  PAYPAL( "fa-paypal"),
  PIED_PIPER( "fa-pied-piper"),
  PIED_PIPER_ALT( "fa-pied-piper-alt"),
  PINTEREST( "fa-pinterest"),
  PINTEREST_SQUARE( "fa-pinterest-square"),
  QQ( "fa-qq"),
  RA( "fa-ra"),
  REBEL( "fa-rebel"),
  REDDIT( "fa-reddit"),
  REDDIT_SQUARE( "fa-reddit-square"),
  RENREN( "fa-renren"),
  SHARE_ALT( "fa-share-alt"),
  SHARE_ALT_SQUARE( "fa-share-alt-square"),
  SKYPE( "fa-skype"),
  SLACK( "fa-slack"),
  SLIDESHARE( "fa-slideshare"),
  SOUNDCLOUD( "fa-soundcloud"),
  SPOTIFY( "fa-spotify"),
  STACK_EXCHANGE( "fa-stack-exchange"),
  STACK_OVERFLOW( "fa-stack-overflow"),
  STEAM( "fa-steam"),
  STEAM_SQUARE( "fa-steam-square"),
  STUMBLEUPON( "fa-stumbleupon"),
  STUMBLEUPON_CIRCLE( "fa-stumbleupon-circle"),
  TENCENT_WEIBO( "fa-tencent-weibo"),
  TRELLO( "fa-trello"),
  TUMBLR( "fa-tumblr"),
  TUMBLR_SQUARE( "fa-tumblr-square"),
  TWITCH( "fa-twitch"),
  TWITTER( "fa-twitter"),
  TWITTER_SQUARE( "fa-twitter-square"),
  VIMEO_SQUARE( "fa-vimeo-square"),
  VINE( "fa-vine"),
  VK( "fa-vk"),
  WECHAT( "fa-wechat"),
  WEIBO( "fa-weibo"),
  WEIXIN( "fa-weixin"),
  WINDOWS( "fa-windows"),
  WORDPRESS( "fa-wordpress"),
  XING( "fa-xing"),
  XING_SQUARE( "fa-xing-square"),
  YAHOO( "fa-yahoo"),
  YELP( "fa-yelp"),
  YOUTUBE( "fa-youtube"),
  YOUTUBE_PLAY( "fa-youtube-play"),
  YOUTUBE_SQUARE( "fa-youtube-square"),
  AMBULANCE( "fa-ambulance"),
  H_SQUARE( "fa-h-square"),
  HOSPITAL_O( "fa-hospital-o"),
  MEDKIT( "fa-medkit"),
  PLUS_SQUARE( "fa-plus-square"),
  STETHOSCOPE( "fa-stethoscope"),
  USER_MD( "fa-user-md"),
  WHEELCHAIR( "fa-wheelchair");
  
  private String key;
  
  private FontAwesome(String key) {
    this.key = key;
  }
  
  public String key() {
    return key;
  }
  
  public UIComponent asComponent(){
    Tag<SpanElement> icon = Tag.asSpan();
    icon.css().set("fa").append(this.key).append(Styles.LARGE);
    return icon;
  }

  public <C extends UIComponent> void appendTo(C component) {
    UIComponent icon = this.asComponent();
    component.asComponent().firstChild(icon);
  }
  
  public static class Styles extends CssClass {
    private Styles(String name) {
      super(name);
    }

    @Override
    protected StyleChooser chooser() {
      return STYLES;
    }

    public static final Styles LARGE = new Styles("fa-lg");
    
    public static final Styles TWICE_LARGE = new Styles("fa-2x");
    
    public static final Styles THREE_TIMES_LARGE = new Styles("fa-3x");
    
    public static final Styles FOUR_TIMES_LARGE = new Styles("fa-4x");
    
    public static final Styles FIVE_TIMES_LARGE = new Styles("fa-5x");

    public static final Styles FIXED = new Styles("fa-fw");
    
    public static final Styles BORDERED = new Styles("fa-border");
    
    public static final Styles SPINNING = new Styles("fa-spin");
    
    public static final Styles ROTATE_90 = new Styles("fa-rotate-90");
    
    public static final Styles ROTATE_180 = new Styles("fa-rotate-180");
    
    public static final Styles ROTATE_270 = new Styles("fa-rotate-270");
    
    public static final Styles FLIP_HORIZONTAL = new Styles("fa-flip-horizontal");
    
    public static final Styles FLIP_VERTICAL = new Styles("fa-flip-vertical");
    
    public static final Styles INVERSE = new Styles("fa-inverse");
    
    private static final StyleChooser STYLES = new StyleChooser(LARGE, TWICE_LARGE, THREE_TIMES_LARGE, FOUR_TIMES_LARGE, FIVE_TIMES_LARGE, FIXED, BORDERED, SPINNING, ROTATE_90, ROTATE_180, ROTATE_270, FLIP_HORIZONTAL, FLIP_VERTICAL, INVERSE);
  }
}